CREATE TABLE Customer_Header (
	SET_ID int PRIMARY KEY ,
	CUSTOMER_ID int ,
	CUSTOMER_NAME1 varchar ,
	CUSTOMER_NAME2 varchar ,
	CUSTOMER_NAME3 varchar ,
	RFC_ID varchar ,
	CUSTOMER_EMAIL varchar ,
	ADDRESS_ID int ,
	CONTACT_ID int ,
	CUSTOMER_INDUSTRIES_ID int ,
);

CREATE TABLE Customer_Addresses (
	CUSTOMER_ID int ,
	ADDRESS_ID int PRIMARY KEY ,
	EFFECTIVE_DATE date ,
);

CREATE TABLE Addresses (
	ADDRESS_ID int PRIMARY KEY ,
	LINE_1 varchar ,
	LINE_2 varchar ,
	LINE_3 varchar ,
	ZIP_POSTCODE int ,
	NAME_SETTLEMENT varchar ,
	COUNTRY varchar ,
	ADDRESS_TYPE_CODE varchar ,
	OTHER_DETAILS varchar ,
);

CREATE TABLE Address_type (
	ADDRESS_TYPE_CODE varchar PRIMARY KEY ,
	ADDRESS_TYPE_DESCRIPTION varchar ,
);

CREATE TABLE Zip_Postcode (
	ZIP_POSTCODE_ID int PRIMARY KEY ,
	NAME_PROVINCE varchar ,
	NAME_STATE varchar ,
	NAME_CITY varchar ,
);

CREATE TABLE Customer_Industries (
	CUSTOMER_INDUSTRIES_ID int PRIMARY KEY ,
	INDUSTRY_TYPE varchar ,
	SEGMENT_MARKET varchar ,
);

CREATE TABLE Customer_Contact (
	CUSTOMER_ID int ,
	CONTACT_ID int PRIMARY KEY ,
	EFFECTIVE_DATE date ,
);

CREATE TABLE Contact (
	CONTACT_ID int PRIMARY KEY ,
	CONTACT_TYPE_ID varchar ,
	CONTACT_NAME varchar ,
	CONTACT_MIDLENAME varchar ,
	CONTACT_LASTNAME varchar ,
	CONTACT_POSITION varchar ,
	CONTACT_EMAIL varchar ,
	PHONE_TYPE_ID varchar ,
	PHONE varchar ,
);

CREATE TABLE Contact_Type (
	CONTACT_TYPE_ID varchar PRIMARY KEY ,
	CONTACT_TYPE_DESCRIPTION varchar ,
);

CREATE TABLE Contact_Phone_Type (
	PHONE_TYPE_ID varchar PRIMARY KEY ,
	PHONE_TYPE varchar ,
);

ALTER TABLE Customer_Header ADD CONSTRAINT CUSTOMER_INDUSTRIES_ID_ref_Customer_Header_CUSTOMER_INDUSTRIES_ID
	FOREIGN KEY (CUSTOMER_INDUSTRIES_ID) REFERENCES Customer_Industries (CUSTOMER_INDUSTRIES_ID);

ALTER TABLE Customer_Addresses ADD CONSTRAINT CUSTOMER_ID_ref_Customer_Addresses_CUSTOMER_ID
	FOREIGN KEY (CUSTOMER_ID) REFERENCES Customer_Header (CUSTOMER_ID);
ALTER TABLE Customer_Addresses ADD CONSTRAINT ADDRESS_ID_ref_Customer_Addresses_ADDRESS_ID
	FOREIGN KEY (ADDRESS_ID) REFERENCES Customer_Header (ADDRESS_ID);

ALTER TABLE Addresses ADD CONSTRAINT ADDRESS_ID_ref_Addresses_ADDRESS_ID
	FOREIGN KEY (ADDRESS_ID) REFERENCES Customer_Addresses (ADDRESS_ID);
ALTER TABLE Addresses ADD CONSTRAINT ZIP_POSTCODE_ref_Addresses_ZIP_POSTCODE_ID
	FOREIGN KEY (ZIP_POSTCODE) REFERENCES Zip_Postcode (ZIP_POSTCODE_ID);
ALTER TABLE Addresses ADD CONSTRAINT ADDRESS_TYPE_CODE_ref_Addresses_ADDRESS_TYPE_CODE
	FOREIGN KEY (ADDRESS_TYPE_CODE) REFERENCES Address_type (ADDRESS_TYPE_CODE);

ALTER TABLE Customer_Contact ADD CONSTRAINT CUSTOMER_ID_ref_Customer_Contact_CUSTOMER_ID
	FOREIGN KEY (CUSTOMER_ID) REFERENCES Customer_Header (CUSTOMER_ID);
ALTER TABLE Customer_Contact ADD CONSTRAINT CONTACT_ID_ref_Customer_Contact_CONTACT_ID
	FOREIGN KEY (CONTACT_ID) REFERENCES Customer_Header (CONTACT_ID);

ALTER TABLE Contact ADD CONSTRAINT CONTACT_ID_ref_Contact_CONTACT_ID
	FOREIGN KEY (CONTACT_ID) REFERENCES Customer_Contact (CONTACT_ID);
ALTER TABLE Contact ADD CONSTRAINT CONTACT_TYPE_ID_ref_Contact_CONTACT_TYPE_ID
	FOREIGN KEY (CONTACT_TYPE_ID) REFERENCES Contact_Type (CONTACT_TYPE_ID);
ALTER TABLE Contact ADD CONSTRAINT PHONE_TYPE_ID_ref_Contact_PHONE_TYPE_ID
	FOREIGN KEY (PHONE_TYPE_ID) REFERENCES Contact_Phone_Type (PHONE_TYPE_ID);



