CREATE TABLE Customer_Header (
	SET_ID int PRIMARY KEY ,
	CUSTOMER_ID int ,
	CUSTOMER_NAME1 text ,
	CUSTOMER_NAME2 text ,
	CUSTOMER_NAME3 text ,
	RFC_ID text ,
	CUSTOMER_EMAIL text ,
	ADDRESS_ID int ,
	CONTACT_ID int ,
	CUSTOMER_INDUSTRIES_ID int ,
);

CREATE TABLE Customer_Addresses (
	CUSTOMER_ID int ,
	ADDRESS_ID int PRIMARY KEY ,
	EFFECTIVE_DATE date ,
);

CREATE TABLE Addresses (
	ADDRESS_ID int PRIMARY KEY ,
	LINE_1 text ,
	LINE_2 text ,
	LINE_3 text ,
	ZIP_POSTCODE int ,
	NAME_SETTLEMENT text ,
	COUNTRY text ,
	ADDRESS_TYPE_CODE text ,
	OTHER_DETAILS text ,
);

CREATE TABLE Address_type (
	ADDRESS_TYPE_CODE text PRIMARY KEY ,
	ADDRESS_TYPE_DESCRIPTION text ,
);

CREATE TABLE Zip_Postcode (
	ZIP_POSTCODE_ID int PRIMARY KEY ,
	NAME_PROVINCE text ,
	NAME_STATE text ,
	NAME_CITY text ,
);

CREATE TABLE Customer_Industries (
	CUSTOMER_INDUSTRIES_ID int PRIMARY KEY ,
	INDUSTRY_TYPE text ,
	SEGMENT_MARKET text ,
);

CREATE TABLE Customer_Contact (
	CUSTOMER_ID int ,
	CONTACT_ID int PRIMARY KEY ,
	EFFECTIVE_DATE date ,
);

CREATE TABLE Contact (
	CONTACT_ID int PRIMARY KEY ,
	CONTACT_TYPE_ID varchar ,
	CONTACT_NAME text ,
	CONTACT_MIDLENAME text ,
	CONTACT_LASTNAME text ,
	CONTACT_POSITION text ,
	CONTACT_EMAIL text ,
	PHONE_TYPE_ID varchar ,
	PHONE varchar ,
);

CREATE TABLE Contact_Type (
	CONTACT_TYPE_ID varchar PRIMARY KEY ,
	CONTACT_TYPE_DESCRIPTION text ,
);

CREATE TABLE Contact_Phone_Type (
	PHONE_TYPE_ID varchar PRIMARY KEY ,
	PHONE_TYPE text ,
);

ALTER TABLE Customer_Header ADD CONSTRAINT CUSTOMER_INDUSTRIES_ID_ref_Customer_Header_CUSTOMER_INDUSTRIES_ID
	FOREIGN KEY (CUSTOMER_INDUSTRIES_ID) REFERENCES Customer_Industries (CUSTOMER_INDUSTRIES_ID);

ALTER TABLE Customer_Addresses ADD CONSTRAINT CUSTOMER_ID_ref_Customer_Addresses_CUSTOMER_ID
	FOREIGN KEY (CUSTOMER_ID) REFERENCES Customer_Header (CUSTOMER_ID);
ALTER TABLE Customer_Addresses ADD CONSTRAINT ADDRESS_ID_ref_Customer_Addresses_ADDRESS_ID
	FOREIGN KEY (ADDRESS_ID) REFERENCES Customer_Header (ADDRESS_ID);

ALTER TABLE Addresses ADD CONSTRAINT ADDRESS_ID_ref_Addresses_ADDRESS_ID
	FOREIGN KEY (ADDRESS_ID) REFERENCES Customer_Addresses (ADDRESS_ID);
ALTER TABLE Addresses ADD CONSTRAINT ZIP_POSTCODE_ref_Addresses_ZIP_POSTCODE_ID
	FOREIGN KEY (ZIP_POSTCODE) REFERENCES Zip_Postcode (ZIP_POSTCODE_ID);
ALTER TABLE Addresses ADD CONSTRAINT ADDRESS_TYPE_CODE_ref_Addresses_ADDRESS_TYPE_CODE
	FOREIGN KEY (ADDRESS_TYPE_CODE) REFERENCES Address_type (ADDRESS_TYPE_CODE);

ALTER TABLE Customer_Contact ADD CONSTRAINT CUSTOMER_ID_ref_Customer_Contact_CUSTOMER_ID
	FOREIGN KEY (CUSTOMER_ID) REFERENCES Customer_Header (CUSTOMER_ID);
ALTER TABLE Customer_Contact ADD CONSTRAINT CONTACT_ID_ref_Customer_Contact_CONTACT_ID
	FOREIGN KEY (CONTACT_ID) REFERENCES Customer_Header (CONTACT_ID);

ALTER TABLE Contact ADD CONSTRAINT CONTACT_ID_ref_Contact_CONTACT_ID
	FOREIGN KEY (CONTACT_ID) REFERENCES Customer_Contact (CONTACT_ID);
ALTER TABLE Contact ADD CONSTRAINT CONTACT_TYPE_ID_ref_Contact_CONTACT_TYPE_ID
	FOREIGN KEY (CONTACT_TYPE_ID) REFERENCES Contact_Type (CONTACT_TYPE_ID);
ALTER TABLE Contact ADD CONSTRAINT PHONE_TYPE_ID_ref_Contact_PHONE_TYPE_ID
	FOREIGN KEY (PHONE_TYPE_ID) REFERENCES Contact_Phone_Type (PHONE_TYPE_ID);



